name: auto_aula_console
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_aula_core:
    path: ../auto_aula_core
  hive: ^1.4.4+1
  meta: ^1.3.0
  path: ^1.8.0
  riverpod: ^0.13.0-0

dev_dependencies:
  lint: ^1.0.0
  test: ^1.14.4
