name: auto_aula_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  hive: ^1.4.4+1
  lint: ^1.0.0
  meta: ^1.3.0
  puppeteer: ^1.22.0
  riverpod: ^0.13.0-0

dev_dependencies:
  test: ^1.14.4
